/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_hhu_bsinfo_neutrino_util_FileDescriptor */

#ifndef _Included_de_hhu_bsinfo_neutrino_util_FileDescriptor
#define _Included_de_hhu_bsinfo_neutrino_util_FileDescriptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_hhu_bsinfo_neutrino_util_FileDescriptor
 * Method:    close0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_hhu_bsinfo_neutrino_util_FileDescriptor_close0
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
