/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_hhu_bsinfo_neutrino_util_SystemUtil */

#ifndef _Included_de_hhu_bsinfo_neutrino_util_SystemUtil
#define _Included_de_hhu_bsinfo_neutrino_util_SystemUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_hhu_bsinfo_neutrino_util_SystemUtil
 * Method:    getErrorMessage0
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_hhu_bsinfo_neutrino_util_SystemUtil_getErrorMessage0
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
