/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_hhu_bsinfo_neutrino_data_MemoryUtil */

#ifndef _Included_de_hhu_bsinfo_neutrino_data_MemoryUtil
#define _Included_de_hhu_bsinfo_neutrino_data_MemoryUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_hhu_bsinfo_neutrino_data_MemoryUtil
 * Method:    wrap
 * Signature: (JI)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_de_hhu_bsinfo_neutrino_data_MemoryUtil_wrap
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     de_hhu_bsinfo_neutrino_data_MemoryUtil
 * Method:    getAddress
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_neutrino_data_MemoryUtil_getAddress
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
