/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_hhu_bsinfo_neutrino_util_MemoryUtil */

#ifndef _Included_de_hhu_bsinfo_neutrino_util_MemoryUtil
#define _Included_de_hhu_bsinfo_neutrino_util_MemoryUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_hhu_bsinfo_neutrino_util_MemoryUtil
 * Method:    wrap
 * Signature: (JI)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_de_hhu_bsinfo_neutrino_util_MemoryUtil_wrap
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     de_hhu_bsinfo_neutrino_util_MemoryUtil
 * Method:    getAddress
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_de_hhu_bsinfo_neutrino_util_MemoryUtil_getAddress
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_hhu_bsinfo_neutrino_util_MemoryUtil
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_hhu_bsinfo_neutrino_util_MemoryUtil_free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
