/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_hhu_bsinfo_neutrino_util_EventFileDescriptor */

#ifndef _Included_de_hhu_bsinfo_neutrino_util_EventFileDescriptor
#define _Included_de_hhu_bsinfo_neutrino_util_EventFileDescriptor
#ifdef __cplusplus
extern "C" {
#endif
#undef de_hhu_bsinfo_neutrino_util_EventFileDescriptor_STATUS_OK
#define de_hhu_bsinfo_neutrino_util_EventFileDescriptor_STATUS_OK 0L
#undef de_hhu_bsinfo_neutrino_util_EventFileDescriptor_STATUS_ERROR
#define de_hhu_bsinfo_neutrino_util_EventFileDescriptor_STATUS_ERROR -1L
/*
 * Class:     de_hhu_bsinfo_neutrino_util_EventFileDescriptor
 * Method:    create0
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_de_hhu_bsinfo_neutrino_util_EventFileDescriptor_create0
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_hhu_bsinfo_neutrino_util_EventFileDescriptor
 * Method:    read0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_hhu_bsinfo_neutrino_util_EventFileDescriptor_read0
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_hhu_bsinfo_neutrino_util_EventFileDescriptor
 * Method:    increment0
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_de_hhu_bsinfo_neutrino_util_EventFileDescriptor_increment0
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     de_hhu_bsinfo_neutrino_util_EventFileDescriptor
 * Method:    close0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_hhu_bsinfo_neutrino_util_EventFileDescriptor_close0
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
