/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_hhu_bsinfo_neutrino_util_StructUtil */

#ifndef _Included_de_hhu_bsinfo_neutrino_util_StructUtil
#define _Included_de_hhu_bsinfo_neutrino_util_StructUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_hhu_bsinfo_neutrino_util_StructUtil
 * Method:    getStructInformation
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_de_hhu_bsinfo_neutrino_util_StructUtil_getStructInformation
  (JNIEnv *, jclass, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
