/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_hhu_bsinfo_neutrino_util_Epoll */

#ifndef _Included_de_hhu_bsinfo_neutrino_util_Epoll
#define _Included_de_hhu_bsinfo_neutrino_util_Epoll
#ifdef __cplusplus
extern "C" {
#endif
#undef de_hhu_bsinfo_neutrino_util_Epoll_DEFAULT_SIZE
#define de_hhu_bsinfo_neutrino_util_Epoll_DEFAULT_SIZE 1024L
/*
 * Class:     de_hhu_bsinfo_neutrino_util_Epoll
 * Method:    create0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_hhu_bsinfo_neutrino_util_Epoll_create0
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_hhu_bsinfo_neutrino_util_Epoll
 * Method:    control0
 * Signature: (IIIJ)I
 */
JNIEXPORT jint JNICALL Java_de_hhu_bsinfo_neutrino_util_Epoll_control0
  (JNIEnv *, jclass, jint, jint, jint, jlong);

/*
 * Class:     de_hhu_bsinfo_neutrino_util_Epoll
 * Method:    wait0
 * Signature: (IJII)I
 */
JNIEXPORT jint JNICALL Java_de_hhu_bsinfo_neutrino_util_Epoll_wait0
  (JNIEnv *, jclass, jint, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
