/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_hhu_bsinfo_neutrino_util_StructUtil */

#ifndef _Included_de_hhu_bsinfo_neutrino_util_StructUtil
#define _Included_de_hhu_bsinfo_neutrino_util_StructUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_hhu_bsinfo_neutrino_util_StructUtil
 * Method:    getDeviceAttributes
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_hhu_bsinfo_neutrino_util_StructUtil_getDeviceAttributes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_hhu_bsinfo_neutrino_util_StructUtil
 * Method:    getPortAttributes
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_hhu_bsinfo_neutrino_util_StructUtil_getPortAttributes
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
