/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_hhu_bsinfo_neutrino_util_Epoll */

#ifndef _Included_de_hhu_bsinfo_neutrino_util_Epoll
#define _Included_de_hhu_bsinfo_neutrino_util_Epoll
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_hhu_bsinfo_neutrino_util_Epoll
 * Method:    create
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_hhu_bsinfo_neutrino_util_Epoll_create
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_hhu_bsinfo_neutrino_util_Epoll
 * Method:    control
 * Signature: (IIIJ)I
 */
JNIEXPORT jint JNICALL Java_de_hhu_bsinfo_neutrino_util_Epoll_control
  (JNIEnv *, jclass, jint, jint, jint, jlong);

/*
 * Class:     de_hhu_bsinfo_neutrino_util_Epoll
 * Method:    wait
 * Signature: (IJII)I
 */
JNIEXPORT jint JNICALL Java_de_hhu_bsinfo_neutrino_util_Epoll_wait
  (JNIEnv *, jclass, jint, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
